version: '3.7'

services:

  mysql:
    image: mysql:8.0-debian
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --general-log=true --general-log-file=/tmp/query.log
    platform: linux/x86_64
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql

